# CodeRabbit Configuration for sf-ai-cli-practice-v2
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language Settings
language: ja  # 日本語でレビュー

# Review Settings
reviews:
  # Request changes workflow
  request_changes_workflow: true
  
  # High level summary
  high_level_summary: true
  
  # Poem style (optional, fun feature)
  poem: false
  
  # Review level: chill (less strict) | assertive (more thorough)
  review_level: assertive
  
  # Auto review
  auto_review:
    enabled: true
    # Ignore drafts
    drafts: false

# File Filters
# CodeRabbitは最大80ファイルまで効率的にレビュー可能
path_filters:
  # レビュー対象
  include:
    - "force-app/**/*.cls"           # Apex classes
    - "force-app/**/*.trigger"       # Apex triggers
    - "force-app/**/*.js"            # LWC JavaScript
    - "force-app/**/*.html"          # LWC templates
    - "force-app/**/*.css"           # LWC styles
    - "force-app/**/*-meta.xml"      # Metadata
    - "**/*.yml"                     # GitHub Actions
    - "**/*.yaml"                    # Config files
    - "scripts/**/*.sh"              # Shell scripts
    - "docs/**/*.md"                 # Documentation
  
  # レビュー除外
  exclude:
    - "node_modules/**"
    - "coverage/**"
    - "*.min.js"
    - "package-lock.json"
    - ".sfdx/**"
    - ".sf/**"
    - "certificates/**"              # Security: 証明書は除外

# PR File Count Warning
# 80ファイル超過時に警告（GitHub Actionsでもチェック）
pr_limits:
  max_files: 80
  warning_message: "⚠️ このPRは{count}ファイルを含んでいます。CodeRabbitの最適なレビューのため、80ファイル以下に分割することを推奨します。"

# Code Quality Checks
checks:
  # Salesforce特有のチェック
  salesforce:
    # SOQL/SOSLインジェクション
    soql_injection: true
    # FLS/CRUD権限チェック
    fls_crud: true
    # Governor Limits意識
    governor_limits: true
  
  # 一般的なチェック
  general:
    # セキュリティ
    security: true
    # パフォーマンス
    performance: true
    # ベストプラクティス
    best_practices: true
    # コードスタイル
    style: true

# Knowledge Base
# CodeRabbitに学習させるドキュメント
knowledge_base:
  - "docs/01-development/coding-standards.md"
  - "docs/01-development/testing-guide.md"
  - "docs/00-setup/01-prerequisites.md"
  - "SECURITY.md"

# Custom Instructions
custom_instructions: |
  ## Salesforce開発のレビュー重点項目
  
  ### Apex
  - SOQL/DMLはバルク処理対応しているか
  - Governor Limitsを考慮しているか
  - FLS/CRUD権限チェックは適切か
  - テストカバレッジは90%以上か
  - エラーハンドリングは適切か
  
  ### LWC
  - セキュアなAPI呼び出しか（@wire, Apex呼び出し）
  - エラーハンドリングは適切か
  - ユーザビリティは考慮されているか
  - Jestテストは含まれているか
  
  ### 一般
  - TDD（Test-Driven Development）が実践されているか
  - コメント・ドキュメントは十分か
  - セキュリティリスクはないか
  - コードの再利用性は高いか

# Chat Settings
chat:
  # Enable chat with CodeRabbit
  enabled: true
  
  # Auto-reply to comments
  auto_reply: true

# Learning Settings
learning:
  # Learn from feedback
  enabled: true

---

# レビュー品質向上のTips

## PR作成時のベストプラクティス
1. **小さいPR**: 80ファイル以下、変更行数500行以下が理想
2. **明確な説明**: PRテンプレートを活用
3. **テスト含む**: すべての変更にテストを含める
4. **一貫性**: Prettier/ESLintでフォーマット統一

## CodeRabbitの活用
- レビューコメントには積極的に返信
- 提案された修正は検討して適用
- 学習機能を活用してプロジェクト固有のルール強化
